name: Python package

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: goanpeca/setup-miniconda@v1.0.2
        with:
          auto-update-conda: true
          activate-environment: topy
          environment-file: conda.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      - name: Install ToPy
        shell: bash -l {0}
        run: |
          pip install .
      - name: Run pytest
        shell: bash -l {0}
        run: |
          pytest
